  Main.cpp
f:\2n grado\tecnologia_r\actividadestona\actividades\src\aa2\main.cpp(17): warning C4297: 'SDL_main': se suponía que la función no producía una excepción, pero lo hace
  f:\2n grado\tecnologia_r\actividadestona\actividades\src\aa2\main.cpp(17): note: __declspec(nothrow), throw(), noexcept(true) o noexcept se han especificado en la función
f:\2n grado\tecnologia_r\actividadestona\actividades\src\aa2\main.cpp(22): warning C4297: 'SDL_main': se suponía que la función no producía una excepción, pero lo hace
  f:\2n grado\tecnologia_r\actividadestona\actividades\src\aa2\main.cpp(22): note: __declspec(nothrow), throw(), noexcept(true) o noexcept se han especificado en la función
f:\2n grado\tecnologia_r\actividadestona\actividades\src\aa2\main.cpp(27): warning C4297: 'SDL_main': se suponía que la función no producía una excepción, pero lo hace
  f:\2n grado\tecnologia_r\actividadestona\actividades\src\aa2\main.cpp(27): note: __declspec(nothrow), throw(), noexcept(true) o noexcept se han especificado en la función
f:\2n grado\tecnologia_r\actividadestona\actividades\src\aa2\main.cpp(31): warning C4297: 'SDL_main': se suponía que la función no producía una excepción, pero lo hace
  f:\2n grado\tecnologia_r\actividadestona\actividades\src\aa2\main.cpp(31): note: __declspec(nothrow), throw(), noexcept(true) o noexcept se han especificado en la función
f:\2n grado\tecnologia_r\actividadestona\actividades\src\aa2\main.cpp(34): warning C4297: 'SDL_main': se suponía que la función no producía una excepción, pero lo hace
  f:\2n grado\tecnologia_r\actividadestona\actividades\src\aa2\main.cpp(34): note: __declspec(nothrow), throw(), noexcept(true) o noexcept se han especificado en la función
f:\2n grado\tecnologia_r\actividadestona\actividades\src\aa2\main.cpp(40): warning C4297: 'SDL_main': se suponía que la función no producía una excepción, pero lo hace
  f:\2n grado\tecnologia_r\actividadestona\actividades\src\aa2\main.cpp(40): note: __declspec(nothrow), throw(), noexcept(true) o noexcept se han especificado en la función
f:\2n grado\tecnologia_r\actividadestona\actividades\src\aa2\main.cpp(45): warning C4297: 'SDL_main': se suponía que la función no producía una excepción, pero lo hace
  f:\2n grado\tecnologia_r\actividadestona\actividades\src\aa2\main.cpp(45): note: __declspec(nothrow), throw(), noexcept(true) o noexcept se han especificado en la función
f:\2n grado\tecnologia_r\actividadestona\actividades\src\aa2\main.cpp(53): warning C4297: 'SDL_main': se suponía que la función no producía una excepción, pero lo hace
  f:\2n grado\tecnologia_r\actividadestona\actividades\src\aa2\main.cpp(53): note: __declspec(nothrow), throw(), noexcept(true) o noexcept se han especificado en la función
f:\2n grado\tecnologia_r\actividadestona\actividades\src\aa2\main.cpp(55): warning C4297: 'SDL_main': se suponía que la función no producía una excepción, pero lo hace
  f:\2n grado\tecnologia_r\actividadestona\actividades\src\aa2\main.cpp(55): note: __declspec(nothrow), throw(), noexcept(true) o noexcept se han especificado en la función
f:\2n grado\tecnologia_r\actividadestona\actividades\src\aa2\main.cpp(63): warning C4297: 'SDL_main': se suponía que la función no producía una excepción, pero lo hace
  f:\2n grado\tecnologia_r\actividadestona\actividades\src\aa2\main.cpp(63): note: __declspec(nothrow), throw(), noexcept(true) o noexcept se han especificado en la función
f:\2n grado\tecnologia_r\actividadestona\actividades\src\aa2\main.cpp(65): warning C4297: 'SDL_main': se suponía que la función no producía una excepción, pero lo hace
  f:\2n grado\tecnologia_r\actividadestona\actividades\src\aa2\main.cpp(65): note: __declspec(nothrow), throw(), noexcept(true) o noexcept se han especificado en la función
f:\2n grado\tecnologia_r\actividadestona\actividades\src\aa2\main.cpp(73): warning C4297: 'SDL_main': se suponía que la función no producía una excepción, pero lo hace
  f:\2n grado\tecnologia_r\actividadestona\actividades\src\aa2\main.cpp(73): note: __declspec(nothrow), throw(), noexcept(true) o noexcept se han especificado en la función
f:\2n grado\tecnologia_r\actividadestona\actividades\src\aa2\main.cpp(75): warning C4297: 'SDL_main': se suponía que la función no producía una excepción, pero lo hace
  f:\2n grado\tecnologia_r\actividadestona\actividades\src\aa2\main.cpp(75): note: __declspec(nothrow), throw(), noexcept(true) o noexcept se han especificado en la función
  AA2.vcxproj -> F:\2n Grado\Tecnologia_R\ActividadesTona\Actividades\\bin\Win32Debug\AA2.exe
  0 archivo(s) copiado(s)
